### ISSUE TITLE
Example to demonstrate different file operations

### ISSUE THREAD

**Issue by aprabhat** [sagar-jadhav/go-examples#143]
Add code example let say `file_handling.go` which demonstrates following:
- File creation
- Reading file content
- Updating file content
- Deleting file

Do all these operations over `text` file

Refer [Hello World](https://github.com/sagar-jadhav/go-examples/blob/master/src/hello-world.go) for reference

https://golang.org/pkg/os/

**Comment by mishrraG** [comment]
@sagar-jadhav let me work on this
\
