### ISSUE TITLE
Add example to demonstrate reading argument from console

### ISSUE THREAD

**Issue by ghost** [sagar-jadhav/go-examples#149]
Add code example let say `read_from_console.go` which demonstrates following:
- Reading argument from console
- Perform certain operation on the basis of passed argument
- Keep asking argument until user passes `exit` value

Refer [Hello World](https://github.com/sagar-jadhav/go-examples/blob/master/src/hello-world.go) for reference

**Comment by mishrraG** [comment]
@akshayithape096 let me work on this

**Comment by sagar-jadhav** [comment]
[PR](https://github.com/sagar-jadhav/go-examples/pull/150)

**Comment by sagar-jadhav** [comment]
Welcome @mishrraG, Thank you for taking up this issue.
