### ISSUE TITLE
Fix error in struct example

### ISSUE THREAD

**Issue by mmichaelb** [sagar-jadhav/go-examples#19]
The current struct example is not valid because the `fmt.Println` functions are misspelled (`fmt.PrintLn`). In addition to that, the file should definitely be reformatted.

**Comment by bekicelmir** [comment]
I can fix errors in example

**Comment by mmichaelb** [comment]
Hi! Regarding this problem there is already pull request #20, but thanks for your commitment.

**Comment by mmichaelb** [comment]
Pull request #20 was merged into the master branch. Therefore, this issue is resolved and can be closed.
