### ISSUE TITLE
Fix error in interfaces example

### ISSUE THREAD

**Issue by mmichaelb** [sagar-jadhav/go-examples#23]
Currently, the interface example contains a call to the `distance` function which does not exist. Therefore, the `area` interface function should be re-implemented/fixed.

**Comment by sowmiyamuthuraman** [comment]
Hey! I would like to work on this?

**Comment by sagar-jadhav** [comment]
> Hey! I would like to work on this?

@sowmiyamuthuraman Thank you for showing interest in contribution but for this issue #24 PR is already raised.

But there are other [Issues](https://github.com/sagar-jadhav/go-examples/issues) open which you can pick. Let me know if you want any help.

**Comment by mmichaelb** [comment]
Fixed with #24.
