### ISSUE TITLE
Add Document for Closure Program

### ISSUE THREAD

**Issue by sagar-jadhav** [sagar-jadhav/go-examples#44]
Refer below commits:
- [Commit 1](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 2](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 3](https://github.com/sagar-jadhav/go-examples/commit/f47deddb11788383563ff439008bf37f333e92bd)

**Comment by yogesh-desai** [comment]
Hi @sagar-jadhav 
Raised PR:https://github.com/sagar-jadhav/go-examples/pull/79 for the same. Please review and give your feedback.

**Comment by sagar-jadhav** [comment]
> Hi @sagar-jadhav
> Raised PR:#79 for the same. Please review and give your feedback.

@yogesh-desai I have added review comments please have a look and incorporate changes. Thanks
