### ISSUE TITLE
Add Document for Slice Program

### ISSUE THREAD

**Issue by sagar-jadhav** [sagar-jadhav/go-examples#54]
Refer below commits:
- [Commit 1](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 2](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 3](https://github.com/sagar-jadhav/go-examples/commit/f47deddb11788383563ff439008bf37f333e92bd)

**Comment by fadhilnurmahardi** [comment]
I'm on it @sagar-jadhav

**Comment by fadhilnurmahardi** [comment]
I'm already make a PR. please review and merge @sagar-jadhav

**Comment by sagar-jadhav** [comment]
@fadhilnurmahardi thank you for contribution. I have added review comments please have a look and make changes

**Comment by fadhilnurmahardi** [comment]
done bro @sagar-jadhav
