### ISSUE TITLE
Add Document for String Length Program

### ISSUE THREAD

**Issue by sagar-jadhav** [sagar-jadhav/go-examples#55]
Refer below commits:
- [Commit 1](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 2](https://github.com/sagar-jadhav/go-examples/commit/1522697baa28bae38b964307b1adc353ff3eab20)
- [Commit 3](https://github.com/sagar-jadhav/go-examples/commit/f47deddb11788383563ff439008bf37f333e92bd)

**Comment by digikin** [comment]
Ill take this one. #Hacktoberfest

**Comment by sagar-jadhav** [comment]
- Move .md in root directory (/) and not in `/docs`
- We don't want a separate `/docs` directory
- Update README accordingly
