### ISSUE TITLE
Suggest domain name 

### ISSUE THREAD

**Issue by sagar-jadhav** [sagar-jadhav/go-examples#60]
My thoughts:
- learngowithexamples
- simplygo

Share your thoughts in comments

**Comment by rajkumarGosavi** [comment]
simplygo

**Comment by ilmanzo** [comment]
letitgo :)

**Comment by amalshaji** [comment]
madeingo

**Comment by amalshaji** [comment]
gomadesimple

**Comment by aprabhat** [comment]
gomadeeasy.in
thegoway.in

**Comment by sagar-jadhav** [comment]
Thank you all of you for your contribution 👍 

We are going with `gomadeeasy.in` domain.
