### ISSUE TITLE
Add code example of format verbs provided in ftm package

### ISSUE THREAD

**Issue by aprabhat** [sagar-jadhav/go-examples#72]
Format 'verbs' are provided by fmt package. Add code snippet to demonstrate where and how to use different format specifiers in golang. For example:

> package main
>
>import (
>	"fmt"
>)
>
>func main() {
>	type coordinate struct {
>		x, y int
>	}
>	c := coordinate{1, 2}
>	fmt.Printf("%v\n", c)  // %v : print structure
>	fmt.Printf("%+v\n", c) // %+v: includes struct field names in output.
>}

**Comment by mlimos** [comment]
@sagar-jadhav hi, can I take this one if nobody else has claimed it?

**Comment by sagar-jadhav** [comment]
> @sagar-jadhav hi, can I take this one if nobody else has claimed it?

Sure you can pick up this issue.
