### ISSUE TITLE
Website GA/Release 1.0 Plan

### ISSUE THREAD

**Issue by sagar-jadhav** [sagar-jadhav/go-examples#85]
I have created this issue to discuss following:

- Release date for GA/Release 1.0
- Next Action Item/Issues make website ready for GA/Release 1.0
- Theme suggestion for website
- List of new examples to be added for  GA/Release 1.0

**Note:** GA = General Availability

@aprabhat , @rajkumarGosavi , @ilmanzo , @davidkroell , @mmichaelb & other contributors Please share your suggestion on all the above points.

**Comment by rajkumarGosavi** [comment]
For GA you should also make example about `go get` and environment setup as these 2 parts are confusing

**Comment by sagar-jadhav** [comment]
> For GA you should also make example about `go get` and environment setup as these 2 parts are confusing

Thank you @rajkumarGosavi 👍 

Can you please create issues regarding same and details about what is expected out of those examples.

**Comment by sagar-jadhav** [comment]
@rajkumarGosavi any update on issues creation? Let me know if you need any help from my side.
